name: Node.js CI

on: push

defaults:
  run:
    working-directory: packages/umbreld

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - format-check
          - lint
          - typecheck:ci
          - test:unit
          - test:integration
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm clean-install
      - run: npm run ${{ matrix.task }}
      - if: startsWith(matrix.task, 'test')
        run: npm run coverage
