name: Node.js CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/umbreld
    strategy:
      fail-fast: false
      matrix:
        task:
          - format:check
          # - lint
          - typecheck
          - test:unit -- --coverage --watch=false
          - test:integration -- --coverage --watch=false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: sudo npm clean-install
      - run: sudo npm run ${{ matrix.task }}
